version: 2.1
jobs:
  code-analysis:
    docker:
      - image: cimg/openjdk:11.0.16
    steps:
      - add_ssh_keys:
          fingerprints:
          - "1e:15:1c:62:4a:55:75:e9:24:1a:ae:6d:3b:5c:80:68"
      - checkout
      - run:
          name: code-coverage
          command: |
            cd /home/circleci/project/
            ls -lrt /home/circleci/project/
            mvn clean verify sonar:sonar -Dsonar.projectKey=sonar-project -Dsonar.projectName='sonar-project' -Dsonar.host.url=http://ec2-3-110-118-101.ap-south-1.compute.amazonaws.com:9000 -Dsonar.token=sqp_f0dc3d706865eaf72e76fc0147b4d43a64dc011c
workflows:
  main-workflow:
    jobs:
      - code-analysis